<a href="https://colab.research.google.com/github/ajayks1974/learning/blob/master/fds/fds_wk10_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

In [29]:
import pandas as pd

#Creating Data frame objects

In [ ]:
arr = np.random.randint(0, 10, (5,3))

In [ ]:
df = pd.DataFrame(arr)

In [ ]:
df

0  1  2
0  0  8  1
1  1  7  9
2  1  1  0
3  0  8  7
4  8  5  1

In [ ]:
df.values

array([[0, 8, 1],
       [1, 7, 9],
       [1, 1, 0],
       [0, 8, 7],
       [8, 5, 1]])

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [ ]:
for c in df.columns:
    print(c)

0
1
2


In [ ]:
df.values[0]

array([0, 8, 1])

In [ ]:
df.values[0,0]

0

In [ ]:
df.values[:,0]

array([0, 1, 1, 0, 8])

In [ ]:
df.values[:,0:2]

array([[0, 8],
       [1, 7],
       [1, 1],
       [0, 8],
       [8, 5]])

In [ ]:
df.index = ['R1','R2','R3','R4','R5']

In [ ]:
df.columns = ['c1','c2','c3']

In [ ]:
df

c1  c2  c3
R1   0   8   1
R2   1   7   9
R3   1   1   0
R4   0   8   7
R5   8   5   1

In [ ]:
df.iloc[0]

c1    0
c2    8
c3    1
Name: R1, dtype: int64

In [ ]:
df['R1']

In [ ]:
df.loc['R1']

c1    0
c2    8
c3    1
Name: R1, dtype: int64

In [ ]:
df.loc['R1','c1']

0

In [ ]:
df.loc[0,0]

TypeError: ignored

In [ ]:
df.loc['R3':'R5', 'c2':'c3']

c2  c3
R3   1   0
R4   8   7
R5   5   1

In [ ]:
type(df.loc['R3':'R5', 'c2':'c3'])

pandas.core.frame.DataFrame

In [ ]:
df.iloc[2:4, 1:2]

c2
R3   1
R4   8

In [ ]:
type(df.iloc[0])

pandas.core.series.Series

In [ ]:
type(df.iloc[:,0])

pandas.core.series.Series

In [ ]:
df.iloc[:,0]

R1    0
R2    1
R3    1
R4    0
R5    8
Name: c1, dtype: int64

In [ ]:
df.shape

(5, 3)

In [ ]:
df.T

R1  R2  R3  R4  R5
c1   0   1   1   0   8
c2   8   7   1   8   5
c3   1   9   0   7   1

#Write a Function to create a data frame

In [ ]:
def create_df(nRows, nCols):
    arr = np.random.randint(0, (nRows*nCols - 1), (nRows,nCols))
    df = pd.DataFrame(arr)
    #df.index = ['R' + str(i) for i in range(1,nRows+1)]
    #df.index = ['R' + str(i) for i in np.arange(1,nRows+1)]
    
    df.index = map(lambda i: 'R' + str(i), range(1,nRows+1))
    df.columns = ['C'+ str(i) for i in range(1,nCols+1)]
    return df

In [ ]:
df = create_df(10,10)

In [ ]:
type([str(i) for i in np.arange(1,100)])

list

#Create Data fram from Data Series

In [30]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146],
                 index = ['Mercury', 'Venus', 'Earth', 'Mars','Jupiter', 'Saturn', 'Uranus', 'Nepture', 'Pluto'])

In [31]:
dia = {'Earth': 12.742,
       'Jupiter': 139.82,
       'Mars': 6.779,
       'Mercury': 4.879,
       'Neptune': 49.244,
       'Saturn': 116.46,
       'Uranus': 50.724,
       'Venus': 12.104}

In [32]:
dia = pd.Series(dia)

In [33]:
df = pd.DataFrame({'Mass': mass, 'Dia': dia})

In [19]:
df['Earth']

KeyError: ignored

In [34]:
df['Mass']['Earth']

5.97

In [21]:
df[0][0]

KeyError: ignored

In [35]:
df.Mass.Earth

5.97

In [36]:
df['pop'] = 0

In [24]:
df

Mass      Dia  pop
Earth       5.9700   12.742    0
Jupiter  1898.0000  139.820    0
Mars        0.6420    6.779    0
Mercury     0.3300    4.879    0
Neptune        NaN   49.244    0
Nepture   102.0000      NaN    0
Pluto       0.0146      NaN    0
Saturn    568.0000  116.460    0
Uranus     86.8000   50.724    0
Venus       4.8700   12.104    0

In [25]:
df['Mass']['Earth']

5.97

In [37]:
df['pop']['Earth'] = 800000000

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [38]:
df

Mass      Dia        pop
Earth       5.9700   12.742  800000000
Jupiter  1898.0000  139.820          0
Mars        0.6420    6.779          0
Mercury     0.3300    4.879          0
Neptune        NaN   49.244          0
Nepture   102.0000      NaN          0
Pluto       0.0146      NaN          0
Saturn    568.0000  116.460          0
Uranus     86.8000   50.724          0
Venus       4.8700   12.104          0

In [39]:
df['Mass'] is df.Mass

True

In [42]:
df['pop'] is df.pop

False

In [49]:
def create_mean_row(df):
    pass