<a href="https://colab.research.google.com/github/ajayks1974/learning/blob/master/fds/fds_wk8_assign_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Case Study

In [3]:
!ls cric_data*

cric_data-200320-181217.tsv


In [4]:
!head cric_data-200320-181217.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


#Tasks
1. Find mean, median, IQR for Sachin, Rahul, and India
2. Find the histogram of Sachin's scores with 10 bins
3. Find mean of Sachin's scores grouped by 25 matches
4. Find mean of Sachin's scores where he has scored century
5. Find mean of Sachin's score when Rahul scored less than 10
6. Find mean of Sachin's scores based on which quartile India's score fall in
7. For every match, who has scored more - Sachin or Rahul
8. How many more runs does Sachin score on average after having scored x runs

In [5]:
import numpy as np

In [6]:
#Find mean, median, IQR for Sachin, Rahul, and India

In [7]:
cric_scores = np.genfromtxt("cric_data-200320-181217.tsv",
                            skip_header = 1,
                            usecols = [1, 2, 3])

In [8]:
cric_scores.shape

(225, 3)

In [9]:
cric_scores[0,2]

342.0

In [10]:
sachin_mean_score = np.mean(cric_scores[:,0])
print("Sachin Mean Score:",sachin_mean_score)
sachin_quartiles = np.percentile(cric_scores[:,0], [25,75])
print("Sachin IQR:",sachin_quartiles[1] - sachin_quartiles[0])

Sachin Mean Score: 39.87555555555556
Sachin IQR: 57.0


In [11]:
rahul_mean_score = np.mean(cric_scores[:,1])
print("Rahul Mean Score:",rahul_mean_score)
rahul_quartiles = np.percentile(cric_scores[:,1], [25,75])
print("Rahul IQR:",rahul_quartiles[1] - rahul_quartiles[0])

Rahul Mean Score: 32.062222222222225
Rahul IQR: 46.0


In [12]:
india_mean_score = np.mean(cric_scores[:,2])
print("India Mean Score:",india_mean_score)
india_quartiles = np.percentile(cric_scores[:,2], [25,75])
print("India IQR:",india_quartiles[1] - india_quartiles[0])

India Mean Score: 220.79555555555555
India IQR: 98.0


In [13]:
np.mean(cric_scores, axis = 0)

array([ 39.87555556,  32.06222222, 220.79555556])

In [14]:
#Find the histogram of Sachin's scores with 10 bins

In [15]:
sachin_hist = np.histogram(cric_scores[:,0],bins=10)

In [16]:
sachin_hist

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [17]:
#Find mean of Sachin's scores grouped by 25 matches

In [80]:
sachin_score_group_by_25 = cric_scores[:,0].reshape(25,-1)

In [81]:
sachin_score_group_by_25.shape

(25, 9)

In [19]:
np.mean(sachin_score_group_by_25, axis = 0)

array([37.04, 45.44, 40.24, 44.76, 51.32, 28.52, 37.88, 32.28, 41.4 ])

In [20]:
#Find mean of Sachin's scores where he has scored century

In [21]:
sachin_scores = cric_scores[:,0]

In [22]:
np.mean(sachin_scores[sachin_scores >= 100])

125.0

In [23]:
np.mean(cric_scores[:,0][cric_scores[:,0] >= 100])

125.0

In [24]:
#Find mean of Sachin's score when Rahul scored less than 10

In [31]:
np.mean(cric_scores[cric_scores[:,1] < 10 ][:,0])

40.74285714285714

In [32]:
#Find mean of Sachin's scores based on which quartile India's score fall in

In [35]:
quartiles = np.percentile(cric_scores[:,2],[0,25,50,75,100])

In [36]:
quartiles

array([  0., 175., 216., 273., 499.])

In [74]:
digitized_list = np.digitize(cric_scores[:,2], list(quartiles))

In [75]:
temp_cric_scores = np.copy(cric_scores)

In [76]:
temp_cric_scores.shape

(225, 3)

In [77]:
temp_cric_scores_1 = np.column_stack((temp_cric_scores,digitized_list))

In [79]:
temp_cric_scores_1.shape

(225, 4)

In [84]:
for iter in range(4):
    print("Sachin Average for Indian Score in Quartile ", iter+1, "is: ", np.mean(temp_cric_scores_1[temp_cric_scores_1[:,3] == iter+1][:,0]))
#np.mean(temp_cric_scores_1[temp_cric_scores_1[:,3] == 4][:,0])

Sachin Average for Indian Score in Quartile  1 is:  19.672727272727272
Sachin Average for Indian Score in Quartile  2 is:  36.535714285714285
Sachin Average for Indian Score in Quartile  3 is:  38.642857142857146
Sachin Average for Indian Score in Quartile  4 is:  63.56140350877193


In [ ]:
"""
For every match, who has scored more - Sachin or Rahul
How many more runs does Sachin score on average after having scored x runs
"""

"\nFind mean of Sachin's scores based on which quartile India's score fall in\nFor every match, who has scored more - Sachin or Rahul\nHow many more runs does Sachin score on average after having scored x runs\n"

In [26]:
"""
Find mean of Sachin's scores based on which quartile India's score fall in
For every match, who has scored more - Sachin or Rahul
How many more runs does Sachin score on average after having scored x runs
"""

"\nFind mean of Sachin's scores based on which quartile India's score fall in\nFor every match, who has scored more - Sachin or Rahul\nHow many more runs does Sachin score on average after having scored x runs\n"