<a href="https://colab.research.google.com/github/ajayks1974/learning/blob/master/fds/fds_wk10_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

#Creating Data frame objects

In [3]:
arr = np.random.randint(0, 10, (5,3))

In [4]:
df = pd.DataFrame(arr)

In [5]:
df

0  1  2
0  2  0  4
1  8  9  0
2  3  9  0
3  9  9  3
4  6  8  8

In [6]:
df.values

array([[2, 0, 4],
       [8, 9, 0],
       [3, 9, 0],
       [9, 9, 3],
       [6, 8, 8]])

In [7]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [9]:
for c in df.columns:
    print(c)

0
1
2


In [10]:
df.values[0]

array([2, 0, 4])

In [11]:
df.values[0,0]

2

In [12]:
df.values[:,0]

array([2, 8, 3, 9, 6])

In [13]:
df.values[:,0:2]

array([[2, 0],
       [8, 9],
       [3, 9],
       [9, 9],
       [6, 8]])

In [14]:
df.index = ['R1','R2','R3','R4','R5']

In [15]:
df.columns = ['c1','c2','c3']

In [16]:
df

c1  c2  c3
R1   2   0   4
R2   8   9   0
R3   3   9   0
R4   9   9   3
R5   6   8   8

In [17]:
df.iloc[0]

c1    2
c2    0
c3    4
Name: R1, dtype: int64

In [18]:
df.loc['R1']

c1    2
c2    0
c3    4
Name: R1, dtype: int64

In [19]:
df.loc['R1','c1']

2

In [20]:
df.loc['R3':'R5', 'c2':'c3']

c2  c3
R3   9   0
R4   9   3
R5   8   8

In [21]:
type(df.loc['R3':'R5', 'c2':'c3'])

pandas.core.frame.DataFrame

In [22]:
df.iloc[2:4, 1:2]

c2
R3   9
R4   9

In [23]:
type(df.iloc[0])

pandas.core.series.Series

In [24]:
type(df.iloc[:,0])

pandas.core.series.Series

In [25]:
df.iloc[:,0]

R1    2
R2    8
R3    3
R4    9
R5    6
Name: c1, dtype: int64

In [26]:
df.shape

(5, 3)

In [27]:
df.T

R1  R2  R3  R4  R5
c1   2   8   3   9   6
c2   0   9   9   9   8
c3   4   0   0   3   8

#Write a Function to create a data frame

In [28]:
def create_df(nRows, nCols):
    arr = np.random.randint(0, (nRows*nCols - 1), (nRows,nCols))
    df = pd.DataFrame(arr)
    #df.index = ['R' + str(i) for i in range(1,nRows+1)]
    #df.index = ['R' + str(i) for i in np.arange(1,nRows+1)]
    
    df.index = map(lambda i: 'R' + str(i), range(1,nRows+1))
    df.columns = ['C'+ str(i) for i in range(1,nCols+1)]
    return df

In [29]:
df = create_df(10,10)

In [30]:
type([str(i) for i in np.arange(1,100)])

list

#Create Data fram from Data Series

In [31]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146],
                 index = ['Mercury', 'Venus', 'Earth', 'Mars','Jupiter', 'Saturn', 'Uranus', 'Nepture', 'Pluto'])

In [32]:
dia = {'Earth': 12.742,
       'Jupiter': 139.82,
       'Mars': 6.779,
       'Mercury': 4.879,
       'Neptune': 49.244,
       'Saturn': 116.46,
       'Uranus': 50.724,
       'Venus': 12.104}

In [33]:
dia = pd.Series(dia)

In [34]:
df = pd.DataFrame({'Mass': mass, 'Dia': dia})

In [35]:
df['Mass']['Earth']

5.97

In [36]:
df.Mass.Earth

5.97

In [37]:
df['pop'] = 0

In [38]:
df

Mass      Dia  pop
Earth       5.9700   12.742    0
Jupiter  1898.0000  139.820    0
Mars        0.6420    6.779    0
Mercury     0.3300    4.879    0
Neptune        NaN   49.244    0
Nepture   102.0000      NaN    0
Pluto       0.0146      NaN    0
Saturn    568.0000  116.460    0
Uranus     86.8000   50.724    0
Venus       4.8700   12.104    0

In [39]:
df['Mass']['Earth']

5.97

In [40]:
df['pop']['Earth'] = 800000000

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [41]:
df

Mass      Dia        pop
Earth       5.9700   12.742  800000000
Jupiter  1898.0000  139.820          0
Mars        0.6420    6.779          0
Mercury     0.3300    4.879          0
Neptune        NaN   49.244          0
Nepture   102.0000      NaN          0
Pluto       0.0146      NaN          0
Saturn    568.0000  116.460          0
Uranus     86.8000   50.724          0
Venus       4.8700   12.104          0

In [42]:
df['Mass'] is df.Mass

True

In [43]:
df['pop'] is df.pop

False

In [44]:
def create_mean_row(df):
    #df.loc['Col_mean'] = [np.mean(df[col]) for col in df.columns]
    df.loc['Col_mean'] = df.mean()

In [45]:
df['pop']=0

In [46]:
df.loc['Col_mean'] = 0

In [47]:
df

Mass      Dia  pop
Earth        5.9700   12.742    0
Jupiter   1898.0000  139.820    0
Mars         0.6420    6.779    0
Mercury      0.3300    4.879    0
Neptune         NaN   49.244    0
Nepture    102.0000      NaN    0
Pluto        0.0146      NaN    0
Saturn     568.0000  116.460    0
Uranus      86.8000   50.724    0
Venus        4.8700   12.104    0
Col_mean     0.0000    0.000    0

In [48]:
np.mean(df['Mass'])

266.66266

In [49]:
df.drop('Col_mean')

Mass      Dia  pop
Earth       5.9700   12.742    0
Jupiter  1898.0000  139.820    0
Mars        0.6420    6.779    0
Mercury     0.3300    4.879    0
Neptune        NaN   49.244    0
Nepture   102.0000      NaN    0
Pluto       0.0146      NaN    0
Saturn    568.0000  116.460    0
Uranus     86.8000   50.724    0
Venus       4.8700   12.104    0

In [50]:
df.drop('Col_mean', inplace=True)

In [51]:
df.drop('pop',axis=1, inplace=True)

In [52]:
df

Mass      Dia
Earth       5.9700   12.742
Jupiter  1898.0000  139.820
Mars        0.6420    6.779
Mercury     0.3300    4.879
Neptune        NaN   49.244
Nepture   102.0000      NaN
Pluto       0.0146      NaN
Saturn    568.0000  116.460
Uranus     86.8000   50.724
Venus       4.8700   12.104

In [53]:
df.loc['Col_mean'] = [np.mean(df['Mass']),np.mean(df['Dia']) ]

In [54]:
df.shape[1]

2

In [55]:
np.amax(df.to_numpy(),axis=0)

array([nan, nan])

In [56]:
df.to_numpy()

array([[5.97000000e+00, 1.27420000e+01],
       [1.89800000e+03, 1.39820000e+02],
       [6.42000000e-01, 6.77900000e+00],
       [3.30000000e-01, 4.87900000e+00],
       [           nan, 4.92440000e+01],
       [1.02000000e+02,            nan],
       [1.46000000e-02,            nan],
       [5.68000000e+02, 1.16460000e+02],
       [8.68000000e+01, 5.07240000e+01],
       [4.87000000e+00, 1.21040000e+01],
       [2.96291844e+02, 4.90940000e+01]])

In [57]:
df2 = create_df(5,3)

In [58]:
df2

C1  C2  C3
R1   1   1   7
R2   3   4   6
R3  11   0   1
R4   5  10   9
R5   6   6   6

In [59]:
df2.mean()

C1    5.2
C2    4.2
C3    5.8
dtype: float64

In [60]:
create_mean_row(df2)

In [61]:
df2

C1    C2   C3
R1         1.0   1.0  7.0
R2         3.0   4.0  6.0
R3        11.0   0.0  1.0
R4         5.0  10.0  9.0
R5         6.0   6.0  6.0
Col_mean   5.2   4.2  5.8

In [62]:
df2.mean(axis=1)

R1          3.000000
R2          4.333333
R3          4.000000
R4          8.000000
R5          6.000000
Col_mean    5.066667
dtype: float64

In [63]:
df2['Row_mean']=df2.mean(axis=1)

In [64]:
df2

C1    C2   C3  Row_mean
R1         1.0   1.0  7.0  3.000000
R2         3.0   4.0  6.0  4.333333
R3        11.0   0.0  1.0  4.000000
R4         5.0  10.0  9.0  8.000000
R5         6.0   6.0  6.0  6.000000
Col_mean   5.2   4.2  5.8  5.066667

In [65]:
df2.min(axis=1)

R1          1.0
R2          3.0
R3          0.0
R4          5.0
R5          6.0
Col_mean    4.2
dtype: float64

In [66]:
df2.quantile(0.25)

C1          3.500000
C2          1.750000
C3          5.850000
Row_mean    4.083333
Name: 0.25, dtype: float64

In [67]:
df2.drop('Row_mean', axis=1)

C1    C2   C3
R1         1.0   1.0  7.0
R2         3.0   4.0  6.0
R3        11.0   0.0  1.0
R4         5.0  10.0  9.0
R5         6.0   6.0  6.0
Col_mean   5.2   4.2  5.8

In [68]:
df.describe()

Mass        Dia
count    10.000000    9.00000
mean    296.291844   49.09400
std     591.882722   48.99913
min       0.014600    4.87900
25%       1.699000   12.10400
50%      46.385000   49.09400
75%     247.718883   50.72400
max    1898.000000  139.82000

In [69]:
planets = pd.DataFrame({'Mass':mass, 'Dia':dia})

In [70]:
planets.describe()

Mass         Dia
count     9.000000    8.000000
mean    296.291844   49.094000
std     627.786429   52.382273
min       0.014600    4.879000
25%       0.642000   10.772750
50%       5.970000   30.993000
75%     102.000000   67.158000
max    1898.000000  139.820000

In [71]:
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [72]:
df = sns.load_dataset('planets')

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [74]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [75]:
df.tail

<bound method NDFrame.tail of                method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]>

In [76]:
df.tail()

method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [77]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

#Drop the row where any of the column value is null

In [78]:
df2 = df.copy()

In [79]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [80]:
for idx in df2.index:
    for col in df2.columns:
        if pd.isnull(df2.loc[idx,col]):
            df2.drop(idx,inplace=True)
            break

In [81]:
for idx in df2.index:
    for itr in df2.loc[idx]:
        if pd.isnull(itr):
            df2.drop(idx,inplace=True)
            break

In [82]:
df2.describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [83]:
for i,r in df2.iterrows():
    if pd.isnull(r).any():
        df2.drop(i, inplace=True)


In [84]:
df2.describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [85]:
df2.describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [86]:
df2.dropna(inplace=True)

In [87]:
df2.describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

#Filter and show only those rows which have planets that are found in 2010 method is 'Radial Velocity' and distance is large that is > 75%

In [88]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 498 entries, 0 to 784
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          498 non-null    object 
 1   number          498 non-null    int64  
 2   orbital_period  498 non-null    float64
 3   mass            498 non-null    float64
 4   distance        498 non-null    float64
 5   year            498 non-null    int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 27.2+ KB


In [89]:
for i,r in df2.iterrows():
    if ((r.loc['year'] != 2010) and (r.loc['year'] != 'Radial Velocity') and (r.loc['distance'] <= df2.describe().loc['75%','distance'])):
        df2.drop(i, inplace=True)

In [90]:
df2.describe()

number  orbital_period        mass    distance         year
count  115.000000      115.000000  115.000000  115.000000   115.000000
mean     1.513043      707.685585    3.311748  105.048087  2009.295652
std      1.202083      935.857918    3.980109   67.627008     2.435029
min      1.000000        2.137500    0.013000    4.700000  2001.000000
25%      1.000000      187.370000    0.897500   57.685000  2008.500000
50%      1.000000      452.800000    1.850000   97.660000  2010.000000
75%      1.500000      830.238500    3.940000  132.105000  2011.000000
max      6.000000     5584.000000   20.600000  354.000000  2013.000000

In [91]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [92]:
df_ = df.copy()
per_75 = df.distance.quantile(0.75)
for i,r in df_.iterrows():
    if r['year'] < 2010:
        df_.drop(i,inplace=True)
        continue
    if r['method'] != 'Radial Velocity' and r['method'] != 'Transit':
        df_.drop(i,inplace=True)
        continue

    if r['distance'] < per_75:
        df_.drop(i,inplace=True)
        continue

In [93]:
df_.describe()

number  orbital_period       mass     distance         year
count  324.000000      324.000000  12.000000   154.000000   324.000000
mean     2.135802       70.534822   3.851250   654.435649  2012.043210
std      1.472161      257.299126   3.685388   527.480906     1.243429
min      1.000000        0.355000   0.340000   180.000000  2010.000000
25%      1.000000        3.731436   1.165000   303.000000  2011.000000
50%      2.000000        9.264922   2.470000   429.000000  2012.000000
75%      2.000000       26.213000   5.618750   800.000000  2013.000000
max      7.000000     3000.000000  11.100000  3200.000000  2014.000000

In [94]:
df_.head()

method  number  orbital_period  mass  distance  year
87   Radial Velocity       1       578.20000   NaN       NaN  2012
88   Radial Velocity       1       392.60000  0.91       NaN  2011
99           Transit       1         6.21229   NaN     380.0  2010
101          Transit       1        13.24060   NaN     345.0  2010
102          Transit       1         2.99433   NaN     560.0  2010

In [95]:
df_ = df.copy()

In [96]:
per_75

178.5

In [97]:
df_.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [98]:
df__ = df_[
    (df_['year'] >= 2010) &
    ((df_['method'] == "Radial Velocity") | (df['method'] == "Transit")) &
    (df_['distance'] > per_75)
]

In [99]:
df__.describe()

number  orbital_period       mass     distance         year
count  154.000000      154.000000   7.000000   154.000000   154.000000
mean     2.045455       55.483100   5.207143   654.435649  2011.448052
std      1.834103      159.178501   3.891918   527.480906     1.078865
min      1.000000        0.742960   1.250000   180.000000  2010.000000
25%      1.000000        3.276083   2.450000   303.000000  2011.000000
50%      1.000000        4.641130   4.000000   429.000000  2011.000000
75%      2.000000       16.228912   7.600000   800.000000  2012.000000
max      7.000000     1022.000000  11.100000  3200.000000  2014.000000

#Modify the Method column to have only the abbreviation

In [100]:
_df_ = df.copy()

In [101]:
for i,r in _df_.iterrows():
    #abr=''
    #for iter in r['method'].split():
    #    abr+=iter[0]
    _df_.loc[i,'method'] = ''.join([x[0] for x in r['method'].split()])

In [102]:
_df_.tail()

method  number  orbital_period  mass  distance  year
1030      T       1        3.941507   NaN     172.0  2006
1031      T       1        2.615864   NaN     148.0  2007
1032      T       1        3.191524   NaN     174.0  2007
1033      T       1        4.125083   NaN     293.0  2008
1034      T       1        4.187757   NaN     260.0  2008

In [103]:
_df_.method.unique()

array(['RV', 'I', 'ETV', 'T', 'A', 'TTV', 'OBM', 'M', 'PT', 'PTV'],
      dtype=object)

In [104]:
short_names = {}
for unq_names in _df_.method.unique():
    short_names[unq_names] = ''.join([x[0] for x in unq_names.split(' ')])

In [105]:
short_names

{'A': 'A',
 'ETV': 'E',
 'I': 'I',
 'M': 'M',
 'OBM': 'O',
 'PT': 'P',
 'PTV': 'P',
 'RV': 'R',
 'T': 'T',
 'TTV': 'T'}

In [106]:
for i,r in _df_.iterrows():
    _df_.loc[i,'short_method'] = short_names.get(r['method'],r['method']) 

In [107]:
_df_.tail()

method  number  orbital_period  mass  distance  year short_method
1030      T       1        3.941507   NaN     172.0  2006            T
1031      T       1        2.615864   NaN     148.0  2007            T
1032      T       1        3.191524   NaN     174.0  2007            T
1033      T       1        4.125083   NaN     293.0  2008            T
1034      T       1        4.187757   NaN     260.0  2008            T

In [108]:
df3 = sns.load_dataset('planets')

In [109]:
def shorten_method(s):
    return short_names.get(s,s)

In [110]:
df3['short_method'] = df3['method'].apply(shorten_method)

In [ ]:
df3

#Count the number of planets discovered for each method
##Process:
1. **Split** the dataframe into smaller chunks(in this case they should have the same method name)
2. **Apply** some function in each of the smaller chunk in this case it is the count function
3. **Aggregate** the results from each chunk together 

In [139]:
df4 = df.copy()

In [113]:
unq_count = {}
for unq_names in df.method.unique():
    unq_count[unq_names] = 0

In [114]:
unq_count

{'Astrometry': 0,
 'Eclipse Timing Variations': 0,
 'Imaging': 0,
 'Microlensing': 0,
 'Orbital Brightness Modulation': 0,
 'Pulsar Timing': 0,
 'Pulsation Timing Variations': 0,
 'Radial Velocity': 0,
 'Transit': 0,
 'Transit Timing Variations': 0}

In [115]:
for i,r in df.iterrows():
    unq_count[r['method']] += 1

In [116]:
unq_count

{'Astrometry': 2,
 'Eclipse Timing Variations': 9,
 'Imaging': 38,
 'Microlensing': 23,
 'Orbital Brightness Modulation': 3,
 'Pulsar Timing': 5,
 'Pulsation Timing Variations': 1,
 'Radial Velocity': 553,
 'Transit': 397,
 'Transit Timing Variations': 4}

In [120]:
d = {}
for m in df4.method.unique():
    d[m] = df4[df4.method == m]['method'].count()

In [ ]:
d

In [152]:
s_all = df4.groupby('method')['method'].count()

In [128]:
df4.groupby('method')['distance'].mean()

method
Astrometry                         17.875000
Eclipse Timing Variations         315.360000
Imaging                            67.715937
Microlensing                     4144.000000
Orbital Brightness Modulation    1180.000000
Pulsar Timing                    1200.000000
Pulsation Timing Variations              NaN
Radial Velocity                    51.600208
Transit                           599.298080
Transit Timing Variations        1104.333333
Name: distance, dtype: float64

#Find out what fraction of planets have been found in the last decade i.e. in 2010s across each of the method
1. **Filter** the data for given condition i.e. the planet found in last decade
2. **Split** in this case across the method
3. **Apply** in this case just the count
4. **Aggregate**

In [129]:
def frac_of_planets_detected_in_2010s(yrs_list):
    dec_2010_count = 0
    for yr in yrs_list.values:
        if yr >= 2010 and yr <= 2020:
            dec_2010_count+=1
    return dec_2010_count / yrs_list.size

In [151]:
s_2010s = df4[
           ((df4['year'] >= 2010) & (df4['year'] <= 2020))
].groupby('method')['method'].count()

#df5 = df4[
#           ((df4['year'] >= 2020) & (df4['year'] <= 2020))
#].groupby('method')['method'].count()

In [153]:
s_2010s / s_all

method
Astrometry                       1.000000
Eclipse Timing Variations        0.666667
Imaging                          0.473684
Microlensing                     0.565217
Orbital Brightness Modulation    1.000000
Pulsar Timing                    0.200000
Pulsation Timing Variations           NaN
Radial Velocity                  0.388788
Transit                          0.843829
Transit Timing Variations        1.000000
Name: method, dtype: float64