<a href="https://colab.research.google.com/github/ajayks1974/learning/blob/master/fds/fds_wk10_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

#Creating Data frame objects

In [3]:
arr = np.random.randint(0, 10, (5,3))

In [4]:
df = pd.DataFrame(arr)

In [ ]:
df

In [6]:
df.values

array([[5, 8, 3],
       [3, 6, 2],
       [2, 4, 3],
       [3, 1, 7],
       [0, 2, 1]])

In [7]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [9]:
for c in df.columns:
    print(c)

0
1
2


In [10]:
df.values[0]

array([5, 8, 3])

In [11]:
df.values[0,0]

5

In [12]:
df.values[:,0]

array([5, 3, 2, 3, 0])

In [13]:
df.values[:,0:2]

array([[5, 8],
       [3, 6],
       [2, 4],
       [3, 1],
       [0, 2]])

In [14]:
df.index = ['R1','R2','R3','R4','R5']

In [15]:
df.columns = ['c1','c2','c3']

In [16]:
df

c1  c2  c3
R1   5   8   3
R2   3   6   2
R3   2   4   3
R4   3   1   7
R5   0   2   1

In [17]:
df.iloc[0]

c1    5
c2    8
c3    3
Name: R1, dtype: int64

In [18]:
df.loc['R1']

c1    5
c2    8
c3    3
Name: R1, dtype: int64

In [19]:
df.loc['R1','c1']

5

In [20]:
df.loc['R3':'R5', 'c2':'c3']

c2  c3
R3   4   3
R4   1   7
R5   2   1

In [21]:
type(df.loc['R3':'R5', 'c2':'c3'])

pandas.core.frame.DataFrame

In [22]:
df.iloc[2:4, 1:2]

c2
R3   4
R4   1

In [23]:
type(df.iloc[0])

pandas.core.series.Series

In [24]:
type(df.iloc[:,0])

pandas.core.series.Series

In [25]:
df.iloc[:,0]

R1    5
R2    3
R3    2
R4    3
R5    0
Name: c1, dtype: int64

In [26]:
df.shape

(5, 3)

In [27]:
df.T

R1  R2  R3  R4  R5
c1   5   3   2   3   0
c2   8   6   4   1   2
c3   3   2   3   7   1

#Write a Function to create a data frame

In [28]:
def create_df(nRows, nCols):
    arr = np.random.randint(0, (nRows*nCols - 1), (nRows,nCols))
    df = pd.DataFrame(arr)
    #df.index = ['R' + str(i) for i in range(1,nRows+1)]
    #df.index = ['R' + str(i) for i in np.arange(1,nRows+1)]
    
    df.index = map(lambda i: 'R' + str(i), range(1,nRows+1))
    df.columns = ['C'+ str(i) for i in range(1,nCols+1)]
    return df

In [29]:
df = create_df(10,10)

In [30]:
type([str(i) for i in np.arange(1,100)])

list

#Create Data fram from Data Series

In [31]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146],
                 index = ['Mercury', 'Venus', 'Earth', 'Mars','Jupiter', 'Saturn', 'Uranus', 'Nepture', 'Pluto'])

In [32]:
dia = {'Earth': 12.742,
       'Jupiter': 139.82,
       'Mars': 6.779,
       'Mercury': 4.879,
       'Neptune': 49.244,
       'Saturn': 116.46,
       'Uranus': 50.724,
       'Venus': 12.104}

In [33]:
dia = pd.Series(dia)

In [34]:
df = pd.DataFrame({'Mass': mass, 'Dia': dia})

In [35]:
df['Mass']['Earth']

5.97

In [36]:
df.Mass.Earth

5.97

In [37]:
df['pop'] = 0

In [38]:
df

Mass      Dia  pop
Earth       5.9700   12.742    0
Jupiter  1898.0000  139.820    0
Mars        0.6420    6.779    0
Mercury     0.3300    4.879    0
Neptune        NaN   49.244    0
Nepture   102.0000      NaN    0
Pluto       0.0146      NaN    0
Saturn    568.0000  116.460    0
Uranus     86.8000   50.724    0
Venus       4.8700   12.104    0

In [39]:
df['Mass']['Earth']

5.97

In [40]:
df['pop']['Earth'] = 800000000

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [41]:
df

Mass      Dia        pop
Earth       5.9700   12.742  800000000
Jupiter  1898.0000  139.820          0
Mars        0.6420    6.779          0
Mercury     0.3300    4.879          0
Neptune        NaN   49.244          0
Nepture   102.0000      NaN          0
Pluto       0.0146      NaN          0
Saturn    568.0000  116.460          0
Uranus     86.8000   50.724          0
Venus       4.8700   12.104          0

In [42]:
df['Mass'] is df.Mass

True

In [43]:
df['pop'] is df.pop

False

In [44]:
def create_mean_row(df):
    #df.loc['Col_mean'] = [np.mean(df[col]) for col in df.columns]
    df.loc['Col_mean'] = df.mean()

In [45]:
df['pop']=0

In [46]:
df.loc['Col_mean'] = 0

In [47]:
df

Mass      Dia  pop
Earth        5.9700   12.742    0
Jupiter   1898.0000  139.820    0
Mars         0.6420    6.779    0
Mercury      0.3300    4.879    0
Neptune         NaN   49.244    0
Nepture    102.0000      NaN    0
Pluto        0.0146      NaN    0
Saturn     568.0000  116.460    0
Uranus      86.8000   50.724    0
Venus        4.8700   12.104    0
Col_mean     0.0000    0.000    0

In [48]:
np.mean(df['Mass'])

266.66266

In [49]:
df.drop('Col_mean')

Mass      Dia  pop
Earth       5.9700   12.742    0
Jupiter  1898.0000  139.820    0
Mars        0.6420    6.779    0
Mercury     0.3300    4.879    0
Neptune        NaN   49.244    0
Nepture   102.0000      NaN    0
Pluto       0.0146      NaN    0
Saturn    568.0000  116.460    0
Uranus     86.8000   50.724    0
Venus       4.8700   12.104    0

In [50]:
df.drop('Col_mean', inplace=True)

In [51]:
df.drop('pop',axis=1, inplace=True)

In [52]:
df

Mass      Dia
Earth       5.9700   12.742
Jupiter  1898.0000  139.820
Mars        0.6420    6.779
Mercury     0.3300    4.879
Neptune        NaN   49.244
Nepture   102.0000      NaN
Pluto       0.0146      NaN
Saturn    568.0000  116.460
Uranus     86.8000   50.724
Venus       4.8700   12.104

In [53]:
df.loc['Col_mean'] = [np.mean(df['Mass']),np.mean(df['Dia']) ]

In [54]:
df.shape[1]

2

In [55]:
np.amax(df.to_numpy(),axis=0)

array([nan, nan])

In [56]:
df.to_numpy()

array([[5.97000000e+00, 1.27420000e+01],
       [1.89800000e+03, 1.39820000e+02],
       [6.42000000e-01, 6.77900000e+00],
       [3.30000000e-01, 4.87900000e+00],
       [           nan, 4.92440000e+01],
       [1.02000000e+02,            nan],
       [1.46000000e-02,            nan],
       [5.68000000e+02, 1.16460000e+02],
       [8.68000000e+01, 5.07240000e+01],
       [4.87000000e+00, 1.21040000e+01],
       [2.96291844e+02, 4.90940000e+01]])

In [57]:
df2 = create_df(5,3)

In [58]:
df2

C1  C2  C3
R1   6   6   4
R2   4   9   4
R3   6   1  11
R4   4   4   6
R5  10   1  11

In [59]:
df2.mean()

C1    6.0
C2    4.2
C3    7.2
dtype: float64

In [60]:
create_mean_row(df2)

In [61]:
df2

C1   C2    C3
R1         6.0  6.0   4.0
R2         4.0  9.0   4.0
R3         6.0  1.0  11.0
R4         4.0  4.0   6.0
R5        10.0  1.0  11.0
Col_mean   6.0  4.2   7.2

In [62]:
df2.mean(axis=1)

R1          5.333333
R2          5.666667
R3          6.000000
R4          4.666667
R5          7.333333
Col_mean    5.800000
dtype: float64

In [63]:
df2['Row_mean']=df2.mean(axis=1)

In [64]:
df2

C1   C2    C3  Row_mean
R1         6.0  6.0   4.0  5.333333
R2         4.0  9.0   4.0  5.666667
R3         6.0  1.0  11.0  6.000000
R4         4.0  4.0   6.0  4.666667
R5        10.0  1.0  11.0  7.333333
Col_mean   6.0  4.2   7.2  5.800000

In [65]:
df2.min(axis=1)

R1          4.0
R2          4.0
R3          1.0
R4          4.0
R5          1.0
Col_mean    4.2
dtype: float64

In [66]:
df2.quantile(0.25)

C1          4.500000
C2          1.750000
C3          4.500000
Row_mean    5.416667
Name: 0.25, dtype: float64

In [67]:
df2.drop('Row_mean', axis=1)

C1   C2    C3
R1         6.0  6.0   4.0
R2         4.0  9.0   4.0
R3         6.0  1.0  11.0
R4         4.0  4.0   6.0
R5        10.0  1.0  11.0
Col_mean   6.0  4.2   7.2

In [68]:
df.describe()

Mass        Dia
count    10.000000    9.00000
mean    296.291844   49.09400
std     591.882722   48.99913
min       0.014600    4.87900
25%       1.699000   12.10400
50%      46.385000   49.09400
75%     247.718883   50.72400
max    1898.000000  139.82000

In [69]:
planets = pd.DataFrame({'Mass':mass, 'Dia':dia})

In [70]:
planets.describe()

Mass         Dia
count     9.000000    8.000000
mean    296.291844   49.094000
std     627.786429   52.382273
min       0.014600    4.879000
25%       0.642000   10.772750
50%       5.970000   30.993000
75%     102.000000   67.158000
max    1898.000000  139.820000

In [72]:
import seaborn as sns

In [73]:
df = sns.load_dataset('planets')

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [76]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [77]:
df.tail

<bound method NDFrame.tail of                method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]>

In [78]:
df.tail()

method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [ ]:
df.describe()

#Drop the row where any of the column value is null

In [110]:
df2 = df.copy()

In [95]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [96]:
for idx in df2.index:
    for col in df2.columns:
        if pd.isnull(df2.loc[idx,col]):
            df2.drop(idx,inplace=True)
            break

In [ ]:
for idx in df2.index:
    for itr in df2.loc[idx]:
        if pd.isnull(itr):
            df2.drop(idx,inplace=True)
            break

In [97]:
df2.describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [104]:
for i,r in df2.iterrows():
    if pd.isnull(r).any():
        df2.drop(i, inplace=True)


In [105]:
df2.describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [107]:
df2.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [108]:
df2.dropna(inplace=True)

In [113]:
df2.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

#Filter and show only those rows which have planets that are found in 2010 method is 'Radial Velocity' and distance is large that is > 75%

In [111]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   method          1035 non-null   object 
 1   number          1035 non-null   int64  
 2   orbital_period  992 non-null    float64
 3   mass            513 non-null    float64
 4   distance        808 non-null    float64
 5   year            1035 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 48.6+ KB


In [118]:
for i,r in df2.iterrows():
    if ((r.loc['year'] != 2010) and (r.loc['year'] != 'Radial Velocity') and (r.loc['distance'] <= df2.describe().loc['75%','distance'])):
        df2.drop(i, inplace=True)

In [ ]:
df2.describe()

In [126]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [127]:
df_ = df.copy()
per_75 = df.distance.quantile(0.75)
for i,r in df_.iterrows():
    if r['year'] < 2010:
        df_.drop(i,inplace=True)
        continue
    if r['method'] != 'Radial Velocity' and r['method'] != 'Transit':
        df_.drop(i,inplace=True)
        continue

    if r['distance'] < per_75:
        df_.drop(i,inplace=True)
        continue

In [128]:
df_.describe()

number  orbital_period       mass     distance         year
count  324.000000      324.000000  12.000000   154.000000   324.000000
mean     2.135802       70.534822   3.851250   654.435649  2012.043210
std      1.472161      257.299126   3.685388   527.480906     1.243429
min      1.000000        0.355000   0.340000   180.000000  2010.000000
25%      1.000000        3.731436   1.165000   303.000000  2011.000000
50%      2.000000        9.264922   2.470000   429.000000  2012.000000
75%      2.000000       26.213000   5.618750   800.000000  2013.000000
max      7.000000     3000.000000  11.100000  3200.000000  2014.000000

In [130]:
df_.head()

method  number  orbital_period  mass  distance  year
87   Radial Velocity       1       578.20000   NaN       NaN  2012
88   Radial Velocity       1       392.60000  0.91       NaN  2011
99           Transit       1         6.21229   NaN     380.0  2010
101          Transit       1        13.24060   NaN     345.0  2010
102          Transit       1         2.99433   NaN     560.0  2010

In [131]:
df_ = df.copy()

In [133]:
per_75

178.5

In [132]:
df_.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [138]:
df__ = df_[
    (df_['year'] >= 2010) &
    ((df_['method'] == "Radial Velocity") | (df['method'] == "Transit")) &
    (df_['distance'] > per_75)
]

In [139]:
df__.describe()

number  orbital_period       mass     distance         year
count  154.000000      154.000000   7.000000   154.000000   154.000000
mean     2.045455       55.483100   5.207143   654.435649  2011.448052
std      1.834103      159.178501   3.891918   527.480906     1.078865
min      1.000000        0.742960   1.250000   180.000000  2010.000000
25%      1.000000        3.276083   2.450000   303.000000  2011.000000
50%      1.000000        4.641130   4.000000   429.000000  2011.000000
75%      2.000000       16.228912   7.600000   800.000000  2012.000000
max      7.000000     1022.000000  11.100000  3200.000000  2014.000000

#Modify the Method column to have only the abbreviation

In [167]:
_df_ = df.copy()

In [158]:
for i,r in _df_.iterrows():
    #abr=''
    #for iter in r['method'].split():
    #    abr+=iter[0]
    _df_.loc[i,'method'] = ''.join([x[0] for x in r['method'].split()])

In [153]:
_df_.tail()

method  number  orbital_period  mass  distance  year
1030      T       1        3.941507   NaN     172.0  2006
1031      T       1        2.615864   NaN     148.0  2007
1032      T       1        3.191524   NaN     174.0  2007
1033      T       1        4.125083   NaN     293.0  2008
1034      T       1        4.187757   NaN     260.0  2008

In [154]:
_df_.method.unique()

array(['RV', 'I', 'ETV', 'T', 'A', 'TTV', 'OBM', 'M', 'PT', 'PTV'],
      dtype=object)

In [160]:
short_names = {}
for unq_names in _df_.method.unique():
    short_names[unq_names] = ''.join([x[0] for x in unq_names.split(' ')])

In [161]:
short_names

{'Astrometry': 'A',
 'Eclipse Timing Variations': 'ETV',
 'Imaging': 'I',
 'Microlensing': 'M',
 'Orbital Brightness Modulation': 'OBM',
 'Pulsar Timing': 'PT',
 'Pulsation Timing Variations': 'PTV',
 'Radial Velocity': 'RV',
 'Transit': 'T',
 'Transit Timing Variations': 'TTV'}

In [168]:
for i,r in _df_.iterrows():
    _df_.loc[i,'short_method'] = short_names.get(r['method'],r['method']) 

In [ ]:
_df_.tail()

In [173]:
df3 = sns.load_dataset('planets')

In [ ]:
def shorten_method(s):
    return short_names.get(s,s)

In [174]:
df3['short_method'] = df3['method'].apply(shorten_method)

In [175]:
df3

method  number  orbital_period  ...  distance  year  short_method
0     Radial Velocity       1      269.300000  ...     77.40  2006            RV
1     Radial Velocity       1      874.774000  ...     56.95  2008            RV
2     Radial Velocity       1      763.000000  ...     19.84  2011            RV
3     Radial Velocity       1      326.030000  ...    110.62  2007            RV
4     Radial Velocity       1      516.220000  ...    119.47  2009            RV
...               ...     ...             ...  ...       ...   ...           ...
1030          Transit       1        3.941507  ...    172.00  2006             T
1031          Transit       1        2.615864  ...    148.00  2007             T
1032          Transit       1        3.191524  ...    174.00  2007             T
1033          Transit       1        4.125083  ...    293.00  2008             T
1034          Transit       1        4.187757  ...    260.00  2008             T

[1035 rows x 7 columns]

#Count the number of planets discovered for each method