<a href="https://colab.research.google.com/github/ajayks1974/learning/blob/master/fds/fds_wk8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Comparing performance Numpy with lists etc

# New Section

In [82]:
import numpy as np

# New Section

In [ ]:
N = 100000000

In [ ]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 18.8 s, sys: 3.43 s, total: 22.2 s
Wall time: 22.2 s


In [ ]:
%%time
list_ = list(range(N))
list__ = [item * item for item in list_]

In [ ]:
%%time
list_ = list(range(N))
list__ = map(lambda x: x * x, list_)

In [ ]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

In [ ]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

In [ ]:
%%time
arr = np.arange(N)
arr = arr * arr

In [ ]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

#Creating np arrays

In [ ]:
arr = np.arange(5)

In [ ]:
print(arr,type(arr))

In [ ]:
arr = np.array([0,1,2,3,4])

In [ ]:
print(arr,type(arr))

In [ ]:
arr

In [ ]:
arr.dtype

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
type(arr.shape)

In [ ]:
arr.size

In [ ]:
arr.itemsize

In [ ]:
arr = np.array([0.0,1,2,3,4])

In [ ]:
arr

In [ ]:
arr.dtype

In [ ]:
arr2d = np.array([
                  [1,2,3],
                  [4,5,6]
])

In [ ]:
arr2d

In [ ]:
arr2d.shape

In [ ]:
arr2d.ndim

In [ ]:
arr2d.dtype

In [ ]:
arr2d.size

In [ ]:
arr2d.itemsize

In [ ]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10,11,12]
                  ]
])

In [ ]:
arr3d

In [ ]:
arr3d.shape

In [ ]:
arr3d.ndim

In [ ]:
arr3d.size

In [ ]:
arr3d.itemsize

In [ ]:
np.ones((2,3,4))

In [ ]:
1729 * np.ones((2,3,4))

In [ ]:
np.zeros((2,3,4))

In [ ]:
np.random.randn(2,3)

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.rand(10,1)

In [ ]:
np.random.randint(0,100,(2,3))

In [ ]:
np.random.randint(0,100,(10,10))

In [ ]:
100 * np.random.rand(10,10)

In [ ]:
np.arange(7,70,7)

In [ ]:
np.linspace(7,70,10)

In [ ]:
bool_arr = np.array([True, False,True, False])

In [ ]:
str_array = np.array(['1.4', '2.1','1.1'])

In [ ]:
bool_arr.itemsize

In [ ]:
bool_arr.dtype

In [ ]:
str_array.dtype

In [ ]:
str_array.itemsize

In [ ]:
str_array.size

In [ ]:
arr = np.array(str_array,dtype='float')

In [ ]:
arr

In [ ]:
arr.dtype

In [ ]:
arr.itemsize

In [ ]:
arr.size

#Indexing

In [ ]:
arr3d[0,0,0]

1

In [ ]:
arr3d[1,0,2]

9

In [ ]:
i = 1
j = 0
k = 2
arr3d[i,j,k]

9

In [ ]:
arr_split = arr3d[0,:,:]

In [ ]:
arr_split.shape

(2, 3)

In [ ]:
arr_split

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_split = arr3d[:,1,:]

In [ ]:
arr_split

array([[ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
arr_split.ndim

2

In [ ]:
arr_split.shape

(2, 2, 2)

In [ ]:
arr_split = arr3d[:,:,0:2]

In [ ]:
arr_split

3

In [ ]:
arr_split.shape

(2, 2, 2)

In [ ]:
arr_split.ndim

3

In [ ]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [ ]:
arr3d[arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
arr3d[(arr3d % 2 == 1) & (arr3d > 5)]

array([ 7,  9, 11])

In [ ]:
arr_slice = arr3d[:,:,0:2]

In [ ]:
arr_slice[0,0,0] = 1729

In [ ]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [ ]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [ ]:
arr_slice_copy = np.copy(arr3d[:,:,0:2])

In [ ]:
arr3d[0,0,0] = 1

In [ ]:
arr_slice_copy[0,0,0] = 1729

In [ ]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [ ]:
arr = np.random.randint(0, 10, (5))

In [ ]:
arr

array([5, 7, 4, 9, 0])

In [ ]:
arr1 = np.random.randint(0, 10, (5,1))

In [ ]:
arr1

array([[8],
       [8],
       [0],
       [0],
       [0]])

In [ ]:
indices = [1,3,4]

In [ ]:
arr[indices]

array([7, 9, 0])

#Numpy Operations

In [ ]:
arr1 = np.zeros((3,4))

In [ ]:
arr2 = np.ones((3,4))

In [ ]:
arr1 + arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr1 - arr2

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [ ]:
arr2 - arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr1 * arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr1 / arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2 / arr1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [ ]:
np.exp(arr1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.exp(arr2)

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183]])

In [ ]:
np.log(arr2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.log(arr1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [ ]:
np.sin(arr1)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.cos(arr1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.sqrt(arr2)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr_inv = 1 / arr2

In [ ]:
arr_inv

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr_inv = 1 / arr1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [ ]:
np.isinf(arr_inv[0,0])

True

#Numpy Broadcasting

In [ ]:
arr1 = np.arange(6)

In [ ]:
arr1.shape

(6,)

In [ ]:
arr1 = arr1.reshape((3,2))

In [ ]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr2 = np.arange(6).reshape((3,2))

In [ ]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
arr1 + arr2[0].reshape((1,2))

array([[0, 2],
       [2, 4],
       [4, 6]])

In [ ]:
arr2[0].reshape((1,2))

array([[0, 1]])

In [ ]:
arr2[:,0].reshape((3,1))

array([[0],
       [2],
       [4]])

In [ ]:
arr1 + arr2[:,0].reshape((3,1))

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
arr1 = np.zeros((3,4))

In [ ]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2 = np.arange(6).reshape((3,2))

In [ ]:
arr2 = np.arange(3).reshape((3,1))

In [ ]:
arr2 + arr1

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [ ]:
arr1 = np.arange(24).reshape((2,3,4))

In [ ]:
arr2 = np.ones((1,4))

In [ ]:
arr1 + arr2

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

#File Handling

In [ ]:
plants_small = np.loadtxt("planets_small-200320-181217.txt", 
                       skiprows = 1,
                       usecols = (1,2,3,4,5,6,7,8,9))

In [ ]:
plants_small.ndim

2

In [ ]:
plants_small.shape

(3, 9)

In [ ]:
plants_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [ ]:
planets = np.genfromtxt("planets-200320-181217.txt",
                        skip_header = 1,
                        usecols = [1,2,3,4,5,6,7,8,9])

In [ ]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [ ]:
planets.size

180

In [ ]:
planets.shape

(20, 9)

In [ ]:
np.isnan(plants)

NameError: ignored

In [ ]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [ ]:
planets_new = np.nan_to_num(planets,nan=-1)

In [ ]:
planets_new

In [ ]:
planets_new.dtype

In [ ]:
np.savetxt('planets_new.txt', planets_new, delimiter=',')

In [ ]:
np.save("planets_new", planets_new)

In [ ]:
!ls

sample_data


In [ ]:
!ls -l

In [ ]:
!ls -lh

In [ ]:
arr1 = np.random.rand(1000, 10)
arr2 = np.random.rand(2000, 5)
arr3 = np.random.rand(20, 10000)


In [ ]:
np.savez("many_arrays", arr1, arr2, arr3)

In [ ]:
!ls -lh

In [ ]:
arrs = np.load('many_arrays.npz')

In [ ]:
arrs.type

In [ ]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [ ]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [ ]:
arrs['arr_0'].shape

(1000, 10)

In [ ]:
arrs['arr_0'][0,0]

0.8170328732069082

In [ ]:
arrs['arr_0']

array([[0.81703287, 0.11857987, 0.30461208, ..., 0.1580477 , 0.04798478,
        0.3247678 ],
       [0.11988019, 0.05791491, 0.57374716, ..., 0.54787777, 0.36957234,
        0.44784531],
       [0.30107328, 0.12838813, 0.02518844, ..., 0.9309684 , 0.96485922,
        0.74648608],
       ...,
       [0.69423504, 0.5553746 , 0.7578684 , ..., 0.39124022, 0.96226759,
        0.17809584],
       [0.16791714, 0.74002958, 0.60725485, ..., 0.2805913 , 0.44179223,
        0.93974497],
       [0.19898519, 0.52803865, 0.84022197, ..., 0.97513595, 0.83443212,
        0.21494034]])

In [ ]:
np.savez_compressed('many_arrs_comprsd',arr1,arr2,arr3)

In [ ]:
!ls -hl

total 3.4M
-rw-r--r-- 1 root root 1.7M Jul  3 10:40 many_arrays.npz
-rw-r--r-- 1 root root 1.6M Jul  3 10:44 many_arrs_comprsd.npz
-rw-r--r-- 1 root root 1.5K Jul  3 10:26 planets-200320-181217.txt
-rw-r--r-- 1 root root 1.6K Jul  3 10:36 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jul  3 10:35 planets_new.txt
-rw-r--r-- 1 root root 4.5K Jul  3 10:34 planets_nex,txt
-rw-r--r-- 1 root root 4.5K Jul  3 10:35 planets_nex.txt
-rw-r--r-- 1 root root  254 Jul  3 09:47 planets_small-200320-181217.txt
drwxr-xr-x 1 root root 4.0K Jun 26 16:26 sample_data


In [ ]:
!ls -lh

total 3.4M
-rw-r--r-- 1 root root 1.7M Jul  3 10:40 many_arrays.npz
-rw-r--r-- 1 root root 1.6M Jul  3 10:44 many_arrs_comprsd.npz
-rw-r--r-- 1 root root 1.5K Jul  3 10:26 planets-200320-181217.txt
-rw-r--r-- 1 root root 1.6K Jul  3 10:36 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jul  3 10:35 planets_new.txt
-rw-r--r-- 1 root root 4.5K Jul  3 10:34 planets_nex,txt
-rw-r--r-- 1 root root 4.5K Jul  3 10:35 planets_nex.txt
-rw-r--r-- 1 root root  254 Jul  3 09:47 planets_small-200320-181217.txt
drwxr-xr-x 1 root root 4.0K Jun 26 16:26 sample_data


In [ ]:
arr1 = np.zeros((10000,10000))

In [ ]:
np.savez("zeros",arr1)

In [ ]:
np.savez_compressed("zeros_comprsd",arr1)

In [ ]:
!ls -lh

total 767M
-rw-r--r-- 1 root root 1.7M Jul  3 10:40 many_arrays.npz
-rw-r--r-- 1 root root 1.6M Jul  3 10:44 many_arrs_comprsd.npz
-rw-r--r-- 1 root root 1.5K Jul  3 10:26 planets-200320-181217.txt
-rw-r--r-- 1 root root 1.6K Jul  3 10:36 planets_new.npy
-rw-r--r-- 1 root root 4.5K Jul  3 10:35 planets_new.txt
-rw-r--r-- 1 root root 4.5K Jul  3 10:34 planets_nex,txt
-rw-r--r-- 1 root root 4.5K Jul  3 10:35 planets_nex.txt
-rw-r--r-- 1 root root  254 Jul  3 09:47 planets_small-200320-181217.txt
drwxr-xr-x 1 root root 4.0K Jun 26 16:26 sample_data
-rw-r--r-- 1 root root 760K Jul  3 10:46 zeros_comprsd.npz
-rw-r--r-- 1 root root 763M Jul  3 10:46 zeros.npz


#Stats with NumPy

In [ ]:
arr = np.random.rand(10000,)

In [ ]:
np.amin(arr)

3.179747770087893e-06

In [ ]:
np.amax(arr)

0.999766990549871

In [ ]:
np.mean(arr)

0.5009704727227924

In [ ]:
np.var(arr)

0.08402023323066683

In [ ]:
np.std(arr)

0.2898624384611894

In [ ]:
np.median(arr)

0.502919723486772

In [ ]:
np.percentile(arr,50)

0.502919723486772

In [ ]:
np.percentile(arr,60)

0.6037797020191311

In [ ]:
np.percentile(arr,100)

0.999766990549871

In [ ]:
np.percentile(arr,75)

0.7497537718818541

In [ ]:
%%time
iqr = np.percentile(arr,75) - np.percentile(arr,25)

CPU times: user 1.42 ms, sys: 31 µs, total: 1.45 ms
Wall time: 1.33 ms


In [ ]:
iqr

0.5012289320110694

In [ ]:
%%time
quartiles = np.percentile(arr,[25,75])
iqr = quartiles[1] - quartiles[0]

CPU times: user 1.21 ms, sys: 38 µs, total: 1.25 ms
Wall time: 841 µs


In [ ]:
z_score =(arr - np.mean(arr)) / np.std(arr)

In [ ]:
z_score

array([ 0.91710479, -0.83733039, -1.4956239 , ...,  1.575767  ,
       -1.03208573,  0.71808177])

In [ ]:
hist = np.histogram(arr,bins=5)

In [ ]:
hist

In [ ]:
print(type(hist))

<class 'tuple'>


In [ ]:
hist[0].shape

(5,)

In [ ]:
hist[1].ndim

1

In [ ]:
hist[1].shape

(6,)

In [ ]:
np.histogram(arr, bins=[0, 0.25, 0.5, 0.75, 1])

(array([2524, 2446, 2534, 2496]), array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [ ]:
bins = [0, 0.25, 0.5, 0.75, 1]

In [ ]:
np.digitize(arr, bins)

array([4, 2, 1, ..., 4, 1, 3])

In [ ]:
arr1 = np.random.randint(0,10,(10))

In [ ]:
arr1.shape

(10,)

In [ ]:
arr1

array([4, 0, 1, 7, 2, 1, 5, 1, 8, 1])

In [ ]:
bins = [0, 7, 10]

In [ ]:
np.digitize(arr1, bins, right = True)

array([1, 0, 1, 1, 1, 1, 1, 1, 2, 1])

In [ ]:
arr_1 = np.random.randint(50,80,100) #weight

In [ ]:
arr_2 = np.random.randint(150,185,100) #height

In [ ]:
arr_3 = np.random.randint(17,22,100) #age

In [ ]:
arr_2d_1 = np.concatenate((arr_1, arr_2, arr_3 )).reshape(3,100)

In [ ]:
arr_2d_1.ndim

2

In [ ]:
arr_2d_2 = np.vstack((arr_1, arr_2, arr_3))

In [ ]:
np.amin(arr_2d_2, axis = 1)

array([ 50, 151,  17])

In [ ]:
np.amin(arr_2d_1, axis = 1)

array([ 50, 151,  17])

In [ ]:
np.amax(arr_2d_1, axis = 1)

array([ 79, 184,  21])

In [ ]:
np.std(arr_2d_1, axis = 1)

array([9.30515449, 9.83145971, 1.51842023])

In [ ]:
np.mean(arr_2d_1, axis = 1)

array([ 65.29, 166.32,  18.88])

# Checking stats rules with Numpy

## Mean substracted array has zero mean

In [88]:
arr = np.random.rand(1000)

In [89]:
mean = np.mean(arr)

In [90]:
arr1 = arr - mean

In [91]:
np.mean(arr1)

-3.68594044175552e-17

##Computing mean with smaller set of values

In [92]:
arr = np.random.rand(1000)

In [95]:
for k in range(50):
    arr1 = arr[0:k]
    print(k,np.mean(arr1))

0 nan
1 0.38303937089075835
2 0.6437107904749605
3 0.7243586554536162
4 0.6069806868967678
5 0.6121763807753245
6 0.6363491031319958
7 0.6660508939372357
8 0.7065353634991518
9 0.6353146294542831
10 0.5756163413023102
11 0.5865047999216311
12 0.6120453036271823
13 0.5682602184887539
14 0.5957308031847359
15 0.5776979688782493
16 0.5477190207827813
17 0.5672463030638561
18 0.5755830362316645
19 0.5928120428658188
20 0.5855628930748635
21 0.5883092624194853
22 0.5617033347519526
23 0.5796722715626098
24 0.564577542030725
25 0.5562166615837103
26 0.5603689293444593
27 0.5649259515041104
28 0.5716520260601383
29 0.5694841056868256
30 0.5641364114752059
31 0.5734788554695398
32 0.575605412923475
33 0.5734216947674547
34 0.5789958773902308
35 0.5772474405706728
36 0.5850190406747303
37 0.570337286639793
38 0.5600853641801099
39 0.5515287108596048
40 0.539137858345836
41 0.5313507102389984
42 0.5398882162643728
43 0.5424702074400792
44 0.5372800312421122
45 0.5376565922587221
46 0.54059032791

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


In [ ]:
np.cumsum(arr)

In [97]:
np.cumsum(arr) / np.arange(1,1001)

array([0.38303937, 0.64371079, 0.72435866, 0.60698069, 0.61217638,
       0.6363491 , 0.66605089, 0.70653536, 0.63531463, 0.57561634,
       0.5865048 , 0.6120453 , 0.56826022, 0.5957308 , 0.57769797,
       0.54771902, 0.5672463 , 0.57558304, 0.59281204, 0.58556289,
       0.58830926, 0.56170333, 0.57967227, 0.56457754, 0.55621666,
       0.56036893, 0.56492595, 0.57165203, 0.56948411, 0.56413641,
       0.57347886, 0.57560541, 0.57342169, 0.57899588, 0.57724744,
       0.58501904, 0.57033729, 0.56008536, 0.55152871, 0.53913786,
       0.53135071, 0.53988822, 0.54247021, 0.53728003, 0.53765659,
       0.54059033, 0.5456217 , 0.53624013, 0.53772593, 0.54037014,
       0.54393587, 0.53429443, 0.52980936, 0.53187901, 0.52603202,
       0.51838642, 0.52246926, 0.5140078 , 0.50779864, 0.51505251,
       0.5117612 , 0.51534684, 0.50815367, 0.50400591, 0.51120297,
       0.50993442, 0.50575519, 0.50165842, 0.49551475, 0.49103019,
       0.49447143, 0.48820832, 0.49008221, 0.48427457, 0.48205

##Effect of outliers on mean and median

In [107]:
arr = np.random.randint(1,100,100)

In [108]:
np.mean(arr)

48.42

In [109]:
np.median(arr)

47.5

In [110]:
np.std(arr)

29.926971113027793

In [111]:
iqr = np.percentile(arr,75) - np.percentile(arr,25)

In [112]:
iqr

51.75

In [113]:
arr = np.append(arr,[1000,2000])

In [114]:
arr.shape

(102,)

In [115]:
np.mean(arr)

76.88235294117646

In [106]:
np.median(arr)

48.5

In [116]:
np.std(arr)

215.1401865869316

In [117]:
iqr = np.percentile(arr,75) - np.percentile(arr,25)

In [118]:
iqr

53.5

##Effect of scaling arrays

In [119]:
arr = np.random.rand(100)

In [120]:
np.mean(arr)

0.5056864118288038

In [121]:
np.median(arr)

0.5118008444627986

In [122]:
arr1 = 2.5 * arr + 0.65

In [123]:
print(np.mean(arr1), 2.5 * np.mean(arr) + 0.65 )

1.9142160295720092 1.9142160295720094


In [124]:
print(np.median(arr1), 2.5 * np.median(arr) + 0.65 )

1.9295021111569965 1.9295021111569963


In [125]:
print(np.var(arr1), 2.5 * 2.5 * np.var(arr))

0.5182014099070267 0.5182014099070267


In [126]:
print(np.std(arr1), 2.5 * np.std(arr))

0.7198620770029678 0.7198620770029678


In [128]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [129]:
print(np.mean(0.21 * arr1 - 0.75 * arr2),
      0.21 * np.mean(arr1) - 0.75 * np.mean(arr2))

-0.2847717952210186 -0.28477179522101853
