<a href="https://colab.research.google.com/github/ajayks1974/learning/blob/master/fds/fds_wk10_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import pandas as pd

#Creating Data frame objects

In [3]:
arr = np.random.randint(0, 10, (5,3))

In [4]:
df = pd.DataFrame(arr)

In [5]:
df

0  1  2
0  5  3  6
1  0  9  7
2  7  9  7
3  3  1  2
4  8  5  6

In [6]:
df.values

array([[5, 3, 6],
       [0, 9, 7],
       [7, 9, 7],
       [3, 1, 2],
       [8, 5, 6]])

In [7]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [9]:
for c in df.columns:
    print(c)

0
1
2


In [10]:
df.values[0]

array([5, 3, 6])

In [11]:
df.values[0,0]

5

In [12]:
df.values[:,0]

array([5, 0, 7, 3, 8])

In [13]:
df.values[:,0:2]

array([[5, 3],
       [0, 9],
       [7, 9],
       [3, 1],
       [8, 5]])

In [14]:
df.index = ['R1','R2','R3','R4','R5']

In [15]:
df.columns = ['c1','c2','c3']

In [16]:
df

c1  c2  c3
R1   5   3   6
R2   0   9   7
R3   7   9   7
R4   3   1   2
R5   8   5   6

In [17]:
df.iloc[0]

c1    5
c2    3
c3    6
Name: R1, dtype: int64

In [19]:
df.loc['R1']

c1    5
c2    3
c3    6
Name: R1, dtype: int64

In [20]:
df.loc['R1','c1']

5

In [21]:
df.loc['R3':'R5', 'c2':'c3']

c2  c3
R3   9   7
R4   1   2
R5   5   6

In [22]:
type(df.loc['R3':'R5', 'c2':'c3'])

pandas.core.frame.DataFrame

In [23]:
df.iloc[2:4, 1:2]

c2
R3   9
R4   1

In [24]:
type(df.iloc[0])

pandas.core.series.Series

In [25]:
type(df.iloc[:,0])

pandas.core.series.Series

In [26]:
df.iloc[:,0]

R1    5
R2    0
R3    7
R4    3
R5    8
Name: c1, dtype: int64

In [27]:
df.shape

(5, 3)

In [28]:
df.T

R1  R2  R3  R4  R5
c1   5   0   7   3   8
c2   3   9   9   1   5
c3   6   7   7   2   6

#Write a Function to create a data frame

In [29]:
def create_df(nRows, nCols):
    arr = np.random.randint(0, (nRows*nCols - 1), (nRows,nCols))
    df = pd.DataFrame(arr)
    #df.index = ['R' + str(i) for i in range(1,nRows+1)]
    #df.index = ['R' + str(i) for i in np.arange(1,nRows+1)]
    
    df.index = map(lambda i: 'R' + str(i), range(1,nRows+1))
    df.columns = ['C'+ str(i) for i in range(1,nCols+1)]
    return df

In [30]:
df = create_df(10,10)

In [31]:
type([str(i) for i in np.arange(1,100)])

list

#Create Data fram from Data Series

In [32]:
mass = pd.Series([0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102, 0.0146],
                 index = ['Mercury', 'Venus', 'Earth', 'Mars','Jupiter', 'Saturn', 'Uranus', 'Nepture', 'Pluto'])

In [33]:
dia = {'Earth': 12.742,
       'Jupiter': 139.82,
       'Mars': 6.779,
       'Mercury': 4.879,
       'Neptune': 49.244,
       'Saturn': 116.46,
       'Uranus': 50.724,
       'Venus': 12.104}

In [34]:
dia = pd.Series(dia)

In [35]:
df = pd.DataFrame({'Mass': mass, 'Dia': dia})

In [ ]:
df['Mass']['Earth']

5.97

In [38]:
df.Mass.Earth

5.97

In [39]:
df['pop'] = 0

In [40]:
df

Mass      Dia  pop
Earth       5.9700   12.742    0
Jupiter  1898.0000  139.820    0
Mars        0.6420    6.779    0
Mercury     0.3300    4.879    0
Neptune        NaN   49.244    0
Nepture   102.0000      NaN    0
Pluto       0.0146      NaN    0
Saturn    568.0000  116.460    0
Uranus     86.8000   50.724    0
Venus       4.8700   12.104    0

In [41]:
df['Mass']['Earth']

5.97

In [42]:
df['pop']['Earth'] = 800000000

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [43]:
df

Mass      Dia        pop
Earth       5.9700   12.742  800000000
Jupiter  1898.0000  139.820          0
Mars        0.6420    6.779          0
Mercury     0.3300    4.879          0
Neptune        NaN   49.244          0
Nepture   102.0000      NaN          0
Pluto       0.0146      NaN          0
Saturn    568.0000  116.460          0
Uranus     86.8000   50.724          0
Venus       4.8700   12.104          0

In [44]:
df['Mass'] is df.Mass

True

In [45]:
df['pop'] is df.pop

False

In [77]:
def create_mean_row(df):
    #df.loc['Col_mean'] = [np.mean(df[col]) for col in df.columns]
    df.loc['Col_mean'] = df.mean()

In [73]:
df['pop']=0

In [75]:
df.loc['Col_mean'] = 0

In [76]:
df

Mass      Dia  pop
Earth        5.9700   12.742    0
Jupiter   1898.0000  139.820    0
Mars         0.6420    6.779    0
Mercury      0.3300    4.879    0
Neptune         NaN   49.244    0
Nepture    102.0000      NaN    0
Pluto        0.0146      NaN    0
Saturn     568.0000  116.460    0
Uranus      86.8000   50.724    0
Venus        4.8700   12.104    0
Col_mean     0.0000    0.000    0

In [56]:
np.mean(df['Mass'])

266.66266

In [57]:
df.drop('Col_mean')

Mass      Dia        pop
Earth       5.9700   12.742  800000000
Jupiter  1898.0000  139.820          0
Mars        0.6420    6.779          0
Mercury     0.3300    4.879          0
Neptune        NaN   49.244          0
Nepture   102.0000      NaN          0
Pluto       0.0146      NaN          0
Saturn    568.0000  116.460          0
Uranus     86.8000   50.724          0
Venus       4.8700   12.104          0

In [59]:
df.drop('Col_mean', inplace=True)

In [60]:
df.drop('pop',axis=1, inplace=True)

In [61]:
df

Mass      Dia
Earth       5.9700   12.742
Jupiter  1898.0000  139.820
Mars        0.6420    6.779
Mercury     0.3300    4.879
Neptune        NaN   49.244
Nepture   102.0000      NaN
Pluto       0.0146      NaN
Saturn    568.0000  116.460
Uranus     86.8000   50.724
Venus       4.8700   12.104

In [62]:
df.loc['Col_mean'] = [np.mean(df['Mass']),np.mean(df['Dia']) ]

In [ ]:
df.shape[1]

In [ ]:
np.amax(df.to_numpy(),axis=0)

In [ ]:
df.to_numpy()

In [78]:
df2 = create_df(5,3)

In [79]:
df2

C1  C2  C3
R1   6   4   9
R2  12  10  13
R3   6   8   9
R4  12  12  10
R5  12  12   7

In [81]:
df2.mean()

C1    9.6
C2    9.2
C3    9.6
dtype: float64

In [82]:
create_mean_row(df2)

In [83]:
df2

C1    C2    C3
R1         6.0   4.0   9.0
R2        12.0  10.0  13.0
R3         6.0   8.0   9.0
R4        12.0  12.0  10.0
R5        12.0  12.0   7.0
Col_mean   9.6   9.2   9.6

In [85]:
df2.mean(axis=1)

R1           6.333333
R2          11.666667
R3           7.666667
R4          11.333333
R5          10.333333
Col_mean     9.466667
dtype: float64

In [86]:
df2['Row_mean']=df2.mean(axis=1)

In [87]:
df2

C1    C2    C3   Row_mean
R1         6.0   4.0   9.0   6.333333
R2        12.0  10.0  13.0  11.666667
R3         6.0   8.0   9.0   7.666667
R4        12.0  12.0  10.0  11.333333
R5        12.0  12.0   7.0  10.333333
Col_mean   9.6   9.2   9.6   9.466667

In [93]:
df2.min(axis=1)

R1           4.0
R2          10.0
R3           6.0
R4          10.0
R5           7.0
Col_mean     9.2
dtype: float64

In [94]:
df2.quantile(0.25)

C1          6.900000
C2          8.300000
C3          9.000000
Row_mean    8.116667
Name: 0.25, dtype: float64

In [95]:
df2.drop('Row_mean', axis=1)

C1    C2    C3
R1         6.0   4.0   9.0
R2        12.0  10.0  13.0
R3         6.0   8.0   9.0
R4        12.0  12.0  10.0
R5        12.0  12.0   7.0
Col_mean   9.6   9.2   9.6

In [96]:
df.describe()

Mass         Dia   pop
count    10.000000    9.000000  11.0
mean    266.662660   43.639111   0.0
std     599.252903   51.659627   0.0
min       0.000000    0.000000   0.0
25%       0.408000    6.779000   0.0
50%       5.420000   12.742000   0.0
75%      98.200000   50.724000   0.0
max    1898.000000  139.820000   0.0

In [98]:
planets = pd.DataFrame({'Mass':mass, 'Dia':dia})

In [99]:
planets.describe()

Mass         Dia
count     9.000000    8.000000
mean    296.291844   49.094000
std     627.786429   52.382273
min       0.014600    4.879000
25%       0.642000   10.772750
50%       5.970000   30.993000
75%     102.000000   67.158000
max    1898.000000  139.820000

In [100]:
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
