<a href="https://colab.research.google.com/github/ajayks1974/learning/blob/master/fds/fds_wk8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Comparing performance Numpy with lists etc

In [1]:
import numpy as np

In [2]:
N = 100000000

In [5]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 18.8 s, sys: 3.43 s, total: 22.2 s
Wall time: 22.2 s


In [ ]:
%%time
list_ = list(range(N))
list__ = [item * item for item in list_]

In [ ]:
%%time
list_ = list(range(N))
list__ = map(lambda x: x * x, list_)

In [ ]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

In [ ]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

In [ ]:
%%time
arr = np.arange(N)
arr = arr * arr

In [ ]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

#Creating np arrays

In [ ]:
arr = np.arange(5)

In [ ]:
print(arr,type(arr))

In [ ]:
arr = np.array([0,1,2,3,4])

In [ ]:
print(arr,type(arr))

In [ ]:
arr

In [ ]:
arr.dtype

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
type(arr.shape)

In [ ]:
arr.size

In [ ]:
arr.itemsize

In [ ]:
arr = np.array([0.0,1,2,3,4])

In [ ]:
arr

In [ ]:
arr.dtype

In [ ]:
arr2d = np.array([
                  [1,2,3],
                  [4,5,6]
])

In [ ]:
arr2d

In [ ]:
arr2d.shape

In [ ]:
arr2d.ndim

In [ ]:
arr2d.dtype

In [ ]:
arr2d.size

In [ ]:
arr2d.itemsize

In [6]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10,11,12]
                  ]
])

In [ ]:
arr3d

In [ ]:
arr3d.shape

In [ ]:
arr3d.ndim

In [ ]:
arr3d.size

In [ ]:
arr3d.itemsize

In [ ]:
np.ones((2,3,4))

In [ ]:
1729 * np.ones((2,3,4))

In [ ]:
np.zeros((2,3,4))

In [ ]:
np.random.randn(2,3)

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.rand(10,1)

In [ ]:
np.random.randint(0,100,(2,3))

In [ ]:
np.random.randint(0,100,(10,10))

In [ ]:
100 * np.random.rand(10,10)

In [ ]:
np.arange(7,70,7)

In [ ]:
np.linspace(7,70,10)

In [ ]:
bool_arr = np.array([True, False,True, False])

In [ ]:
str_array = np.array(['1.4', '2.1','1.1'])

In [ ]:
bool_arr.itemsize

In [ ]:
bool_arr.dtype

In [ ]:
str_array.dtype

In [ ]:
str_array.itemsize

In [ ]:
str_array.size

In [ ]:
arr = np.array(str_array,dtype='float')

In [ ]:
arr

In [ ]:
arr.dtype

In [ ]:
arr.itemsize

In [ ]:
arr.size

#Indexing

In [7]:
arr3d[0,0,0]

1

In [8]:
arr3d[1,0,2]

9

In [9]:
i = 1
j = 0
k = 2
arr3d[i,j,k]

9

In [11]:
arr_split = arr3d[0,:,:]

In [13]:
arr_split.shape

(2, 3)

In [14]:
arr_split

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr_split = arr3d[:,1,:]

In [16]:
arr_split

array([[ 4,  5,  6],
       [10, 11, 12]])

In [17]:
arr_split.ndim

2

In [21]:
arr_split.shape

(2, 2, 2)

In [20]:
arr_split = arr3d[:,:,0:2]

In [19]:
arr_split

3

In [22]:
arr_split.shape

(2, 2, 2)

In [23]:
arr_split.ndim

3

In [24]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [25]:
arr3d[arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [27]:
arr3d[(arr3d % 2 == 1) & (arr3d > 5)]

array([ 7,  9, 11])

In [28]:
arr_slice = arr3d[:,:,0:2]

In [30]:
arr_slice[0,0,0] = 1729

In [31]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [32]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [33]:
arr_slice_copy = np.copy(arr3d[:,:,0:2])

In [34]:
arr3d[0,0,0] = 1

In [35]:
arr_slice_copy[0,0,0] = 1729

In [36]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [38]:
arr = np.random.randint(0, 10, (5))

In [39]:
arr

array([5, 7, 4, 9, 0])

In [40]:
arr1 = np.random.randint(0, 10, (5,1))

In [41]:
arr1

array([[8],
       [8],
       [0],
       [0],
       [0]])

In [42]:
indices = [1,3,4]

In [43]:
arr[indices]

array([7, 9, 0])