<a href="https://colab.research.google.com/github/ajayks1974/learning/blob/master/fds/fds_wk10_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
import pandas as pd

#Creating Data frame objects

In [ ]:
arr = np.random.randint(0, 10, (5,3))

In [ ]:
df = pd.DataFrame(arr)

In [ ]:
df

0  1  2
0  0  8  1
1  1  7  9
2  1  1  0
3  0  8  7
4  8  5  1

In [ ]:
df.values

array([[0, 8, 1],
       [1, 7, 9],
       [1, 1, 0],
       [0, 8, 7],
       [8, 5, 1]])

In [ ]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
df.columns

RangeIndex(start=0, stop=3, step=1)

In [ ]:
for c in df.columns:
    print(c)

0
1
2


In [ ]:
df.values[0]

array([0, 8, 1])

In [ ]:
df.values[0,0]

0

In [ ]:
df.values[:,0]

array([0, 1, 1, 0, 8])

In [ ]:
df.values[:,0:2]

array([[0, 8],
       [1, 7],
       [1, 1],
       [0, 8],
       [8, 5]])

In [ ]:
df.index = ['R1','R2','R3','R4','R5']

In [ ]:
df.columns = ['c1','c2','c3']

In [ ]:
df

c1  c2  c3
R1   0   8   1
R2   1   7   9
R3   1   1   0
R4   0   8   7
R5   8   5   1

In [ ]:
df.iloc[0]

c1    0
c2    8
c3    1
Name: R1, dtype: int64

In [ ]:
df['R1']

In [ ]:
df.loc['R1']

c1    0
c2    8
c3    1
Name: R1, dtype: int64

In [ ]:
df.loc['R1','c1']

0

In [ ]:
df.loc[0,0]

TypeError: ignored

In [ ]:
df.loc['R3':'R5', 'c2':'c3']

c2  c3
R3   1   0
R4   8   7
R5   5   1

In [ ]:
type(df.loc['R3':'R5', 'c2':'c3'])

pandas.core.frame.DataFrame

In [ ]:
df.iloc[2:4, 1:2]

c2
R3   1
R4   8

In [ ]:
type(df.iloc[0])

pandas.core.series.Series

In [ ]:
type(df.iloc[:,0])

pandas.core.series.Series

In [ ]:
df.iloc[:,0]

R1    0
R2    1
R3    1
R4    0
R5    8
Name: c1, dtype: int64

In [ ]:
df.shape

(5, 3)

In [ ]:
df.T

R1  R2  R3  R4  R5
c1   0   1   1   0   8
c2   8   7   1   8   5
c3   1   9   0   7   1

#Write a Function to create a data frame

In [11]:
def create_df(nRows, nCols):
    arr = np.random.randint(0, (nRows*nCols - 1), (nRows,nCols))
    df = pd.DataFrame(arr)
    #df.index = ['R' + str(i) for i in range(1,nRows+1)]
    df.index = map(lambda i: 'R' + str(i), range(1,nRows+1))
    df.columns = ['C'+ str(i) for i in range(1,nCols+1)]
    return df

In [8]:
df = create_df(10,10)

In [ ]:
df