<a href="https://colab.research.google.com/github/ajayks1974/learning/blob/master/fds/fds_wk8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Comparing performance Numpy with lists etc

In [1]:
import numpy as np

In [ ]:
N = 100000000

In [ ]:
%%time
list_ = list(ange(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 18.7 s, sys: 2.43 s, total: 21.1 s
Wall time: 21.1 s


In [ ]:
%%time
list_ = list(range(N))
list__ = [item * item for item in list_]

CPU times: user 8.91 s, sys: 7.9 s, total: 16.8 s
Wall time: 16.8 s


In [ ]:
%%time
list_ = list(range(N))
list__ = map(lambda x: x * x, list_)

CPU times: user 3.25 s, sys: 3.27 s, total: 6.51 s
Wall time: 6.51 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

CPU times: user 11.1 s, sys: 1.26 s, total: 12.4 s
Wall time: 12.4 s


In [ ]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 3.02 s, sys: 2.14 s, total: 5.16 s
Wall time: 5.15 s


In [ ]:
%%time
arr = np.arange(N)
arr = arr * arr

CPU times: user 391 ms, sys: 16.6 ms, total: 407 ms
Wall time: 409 ms


In [ ]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 276 ms, sys: 7.66 ms, total: 284 ms
Wall time: 284 ms


#Creating np arrays

In [2]:
arr = np.arange(5)

In [3]:
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [4]:
arr = np.array([0,1,2,3,4])

In [5]:
print(arr,type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [6]:
arr

array([0, 1, 2, 3, 4])

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr.ndim

1

In [9]:
arr.shape

(5,)

In [10]:
type(arr.shape)

tuple

In [11]:
arr.size

5

In [12]:
arr.itemsize

8

In [16]:
arr = np.array([0.0,1,2,3,4])

In [17]:
arr

array([0., 1., 2., 3., 4.])

In [18]:
arr.dtype

dtype('float64')

In [19]:
arr2d = np.array([
                  [1,2,3],
                  [4,5,6]
])

In [20]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr2d.shape

(2, 3)

In [22]:
arr2d.ndim

2

In [23]:
arr2d.dtype

dtype('int64')

In [24]:
arr2d.size

6

In [25]:
arr2d.itemsize

8

In [26]:
arr3d = np.array([
                  [
                   [1,2,3],
                   [4,5,6]
                  ],
                  [
                   [7,8,9],
                   [10,11,12]
                  ]
])

In [27]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d.shape

(2, 2, 3)

In [29]:
arr3d.ndim

3

In [30]:
arr3d.size

12

In [31]:
arr3d.itemsize

8

In [33]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [34]:
1729 * np.ones((2,3,4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [35]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
np.random.randn(2,3)

array([[-1.00589478, -0.3898828 , -0.85221281],
       [ 0.33750489, -1.67201323,  1.27546523]])

In [37]:
np.random.rand(2,3)

array([[0.65293855, 0.33566872, 0.7951923 ],
       [0.68768021, 0.39753755, 0.54699186]])

In [38]:
np.random.rand(10,1)

array([[0.25803821],
       [0.06859112],
       [0.81441376],
       [0.01781106],
       [0.82113887],
       [0.97163254],
       [0.70132435],
       [0.03206706],
       [0.87595757],
       [0.68838091]])

In [39]:
np.random.randint(0,100,(2,3))

array([[86, 94, 64],
       [66, 12, 81]])

In [40]:
np.random.randint(0,100,(10,10))

array([[92, 38, 76, 28, 98,  2, 52, 10, 73, 42],
       [87, 25, 99, 22, 46, 36, 24, 14, 74, 84],
       [28, 68, 15, 67,  9, 72, 93,  1, 72, 11],
       [34, 34,  7, 10, 81, 64, 37, 48, 80, 75],
       [25, 38, 58, 46, 14, 84,  6, 36, 22, 29],
       [71, 89, 45,  4, 48, 92, 14, 30, 55, 63],
       [21, 82, 86, 82, 86, 64, 63, 92,  5, 58],
       [37, 30, 11, 37, 61, 31, 34, 27, 54, 59],
       [70, 45, 96, 33, 25, 57, 41, 45, 56, 80],
       [58, 42, 16,  3, 77, 11, 71, 53, 42, 93]])

In [41]:
100 * np.random.rand(10,10)

array([[80.69786935, 76.69542721, 17.62814209,  3.80200682, 95.25750426,
        61.82977707, 22.54233457, 34.15568528,  9.4950149 , 97.98347291],
       [49.46427421, 40.86133401, 66.03539183, 92.76412825, 54.21134588,
        13.67914785, 48.16576071, 54.12092223, 16.36744255, 82.61678632],
       [ 3.15150829, 25.84848065, 87.34094369, 49.78940404, 36.73639263,
        79.0657547 , 52.57878627, 16.80684578, 34.0179283 , 99.54556867],
       [68.22322988, 98.46545172, 33.75888994, 46.61830499, 63.16353022,
        57.96593336, 63.98530629, 30.09080339,  2.67483617, 25.47589392],
       [45.0254313 , 20.05927444, 45.65263797, 43.48776465, 83.18442068,
        73.75915102, 29.68760424, 25.9712664 , 14.60089101, 97.65291927],
       [ 2.50232999, 71.73459648, 27.77531788,  7.22030205, 31.6258764 ,
        29.68442208, 78.76869259, 93.92368717, 15.12482542, 34.68777946],
       [57.2063046 , 88.77835277, 71.35370839, 42.01620569, 29.57191525,
        10.52108823, 58.18470171, 77.31081106

In [43]:
np.arange(7,70,7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])

In [44]:
np.linspace(7,70,10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [50]:
bool_arr = np.array([True, False,True, False])

In [56]:
str_array = np.array(['1.4', '2.1','1.1'])

In [54]:
bool_arr.itemsize

1

In [55]:
bool_arr.dtype

dtype('bool')

In [57]:
str_array.dtype

dtype('<U3')

In [58]:
str_array.itemsize

12

In [59]:
str_array.size

3

In [60]:
arr = np.array(str_array,dtype='float')

In [61]:
arr

array([1.4, 2.1, 1.1])

In [62]:
arr.dtype

dtype('float64')

In [63]:
arr.itemsize

8

In [64]:
arr.size

3